### ISSUE TITLE
XenForo language importer doesn't like prettified XML

### ISSUE THREAD

**Issue by besynnerlig** [thaisnack/XF2-Swedish#4]
XenForo language importer doesn't like prettified XML. It seems that XenForo needs each phrase tag to be on a single line. Otherwise the imported phrases will have extra tabs and new line characters.

**Comment by thaisnack** [comment]
Investigating. Meanwhile, until it's fixed, use this version: https://github.com/thaisnack/XF2-Swedish/blob/18f5ed4b263d6638ca397c477d42c2c7e9d2f6c1/language-Swedish-XF.xml

**Comment by thaisnack** [comment]
Rearranged the language file. Solves the problem.
